{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dlstats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dlstats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dlstats/dlstats_{{ version }}.tar.gz
  sha256: 2a6534c03f4883ca49c5cc5c4de57059695ae5a1e34f86e9b2704dfac47d87e1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-jsonlite
    - r-magrittr
    - r-scales
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-jsonlite
    - r-magrittr
    - r-scales

test:
  commands:
    - $R -e "library('dlstats')"           # [not win]
    - "\"%R%\" -e \"library('dlstats')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/dlstats
  license: Artistic-2.0
  summary: Monthly download stats of 'CRAN' and 'Bioconductor' packages. Download stats of 'CRAN' packages is from the 'RStudio' 'CRAN mirror', see <https://cranlogs.r-pkg.org:443>. 'Bioconductor' package download stats is at <https://bioconductor.org/packages/stats/>.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
